#!/bin/bash

export PATH="$PATH":$HOME/src/depot_tools
export GYP_GENERATORS='ninja'
export GYP_DEFINES="clang=1 component=shared_library"
export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox
export GYP_PARALLEL=5

if [[ "$@" == "" ]]; then
  PROMPT_PREFIX="[crosh] " /bin/bash
else
  PROMPT_PREFIX="[crosh] " /bin/bash -c "$@"
fi

